/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScansRouteImport } from './routes/scans'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackingChannelIdRouteImport } from './routes/tracking.$channelId'
import { Route as ChannelsChannelIdRouteImport } from './routes/channels.$channelId'

const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansRoute = ScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingChannelIdRoute = TrackingChannelIdRouteImport.update({
  id: '/$channelId',
  path: '/$channelId',
  getParentRoute: () => TrackingRoute,
} as any)
const ChannelsChannelIdRoute = ChannelsChannelIdRouteImport.update({
  id: '/channels/$channelId',
  path: '/channels/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/scans': typeof ScansRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRouteWithChildren
  '/channels/$channelId': typeof ChannelsChannelIdRoute
  '/tracking/$channelId': typeof TrackingChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/scans': typeof ScansRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRouteWithChildren
  '/channels/$channelId': typeof ChannelsChannelIdRoute
  '/tracking/$channelId': typeof TrackingChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/scans': typeof ScansRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRouteWithChildren
  '/channels/$channelId': typeof ChannelsChannelIdRoute
  '/tracking/$channelId': typeof TrackingChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consent'
    | '/dashboard'
    | '/login'
    | '/scans'
    | '/settings'
    | '/tracking'
    | '/channels/$channelId'
    | '/tracking/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consent'
    | '/dashboard'
    | '/login'
    | '/scans'
    | '/settings'
    | '/tracking'
    | '/channels/$channelId'
    | '/tracking/$channelId'
  id:
    | '__root__'
    | '/'
    | '/consent'
    | '/dashboard'
    | '/login'
    | '/scans'
    | '/settings'
    | '/tracking'
    | '/channels/$channelId'
    | '/tracking/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsentRoute: typeof ConsentRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ScansRoute: typeof ScansRoute
  SettingsRoute: typeof SettingsRoute
  TrackingRoute: typeof TrackingRouteWithChildren
  ChannelsChannelIdRoute: typeof ChannelsChannelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans': {
      id: '/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof ScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking/$channelId': {
      id: '/tracking/$channelId'
      path: '/$channelId'
      fullPath: '/tracking/$channelId'
      preLoaderRoute: typeof TrackingChannelIdRouteImport
      parentRoute: typeof TrackingRoute
    }
    '/channels/$channelId': {
      id: '/channels/$channelId'
      path: '/channels/$channelId'
      fullPath: '/channels/$channelId'
      preLoaderRoute: typeof ChannelsChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TrackingRouteChildren {
  TrackingChannelIdRoute: typeof TrackingChannelIdRoute
}

const TrackingRouteChildren: TrackingRouteChildren = {
  TrackingChannelIdRoute: TrackingChannelIdRoute,
}

const TrackingRouteWithChildren = TrackingRoute._addFileChildren(
  TrackingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsentRoute: ConsentRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ScansRoute: ScansRoute,
  SettingsRoute: SettingsRoute,
  TrackingRoute: TrackingRouteWithChildren,
  ChannelsChannelIdRoute: ChannelsChannelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
